---
# Register on-premise host to amazon ssm
# https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-managedinstances.html

- name: Linux | Register on-premise host
  command: "amazon-ssm-agent -register -code {{ activation_code }} -id {{ activation_id }} -region {{ aws_region }}"
  notify: Linux | Restart amazon ssm agent
  when: ansible_system == "Linux"

- name: Windows | Register on-premise host
  win_shell: |
    Start-Process 'C:\Program Files\Amazon\SSM\amazon-ssm-agent.exe' `
    -ArgumentList @("/q", "/log", "install.log", `
    "CODE={{ activation_code }}", `
    "ID={{ activation_id }}", `
    "REGION={{ aws_region }}") -Wait
  notify: Windows | Restart amazon ssm agent
  when: ansible_system == "Win32NT"
