---
# Install aws ssm agent on Suse family system

- name: Install aws ssm agent on Suse family system
  zypper:
    name: "{{ ssm_package_url }}"
    disable_gpg_check: yes
    state: present

- name: Manage aws ssm agent service on Suse family system
  service:
    name: "{{ ssm_service }}"
    state: started
    enabled: yes
