---
# Install aws ssm agent on Debian family system

- name: Debian | Check if snap is available
  command: snap version
  register: snap_available
  ignore_errors: yes
  changed_when: false
  failed_when: false

- name: Debian | Install with apt aws ssm agent
  apt:
    deb: "{{ ssm_package_url }}"
    state: present
  when: snap_available.rc > 0

- name: Debian | Manage aws ssm agent service
  service:
    name: "{{ ssm_service }}"
    state: started
    enabled: yes
  when: snap_available.rc > 0

- name: Debian | Install with snap aws ssm agent
  command: snap install amazon-ssm-agent --classic
  args:
    creates: /snap/bin/amazon-ssm-agent.ssm-cli
  when: snap_available.rc == 0

- name: Debian | Manage snap aws ssm agent service
  service:
    name: snap.amazon-ssm-agent.amazon-ssm-agent.service
    state: started
    enabled: yes
  when: snap_available.rc == 0

- name: Debian | Configure sudo with aws ssm agent
  copy:
    content: "{{ allow_sudo | ternary('ssm-user ALL=(ALL) NOPASSWD:ALL', '#User rules for ssm-user') }}"
    dest: /etc/sudoers.d/ssm-agent-users
    mode: '0440'
