---
# Install aws ssm agent on Archlinux

- name: Archlinux | Download amazon-ssm-agent
  get_url:
    url: "{{ ssm_package_url }}"
    dest: /usr/bin/amazon-ssm-agent
    mode: '0755'

- name: Archlinux | Amazon ssm agent folder
  file:
    path: /etc/amazon/ssm
    recurse: yes
    owner: root
    group: root
    state: directory

- name: Archlinux | Amazon ssm config
  copy:
    content: "{{ ssm_agent_config | from_json | to_nice_json }}"
    dest: /etc/amazon/ssm/amazon-ssm-agent.json
    owner: root
    group: root
    mode: '0644'

- name: Archlinux | Amazon ssm seelog
  copy:
    content: "{{ ssm_seelog_config }}"
    dest: /etc/amazon/ssm/seelog.xml
    owner: root
    group: root
    mode: '0644'

- name: Archlinux | Systemd configuration
  copy:
    content: "{{ systemd_config }}"
    dest: /etc/systemd/system/amazon-ssm-agent.service
    owner: root
    group: root
    mode: '0644'
  notify: Linux systemd reload

- name: Archlinux | Manage aws ssm agent service
  service:
    name: "{{ ssm_service }}"
    state: started
    enabled: yes

- name: Archlinux | Configure sudo with aws ssm agent
  copy:
    content: "{{ allow_sudo | ternary('ssm-user ALL=(ALL) NOPASSWD:ALL', '#User rules for ssm-user') }}"
    dest: /etc/sudoers.d/ssm-agent-users
    mode: '0440'
