---
# Install aws ssm agent on RedHat family system

- name: yum | Install aws ssm agent
  yum:
    name: "{{ ssm_package_url }}"
    state: present
  when: ansible_pkg_mgr == "yum"

- name: dnf | Install aws ssm agent
  dnf:
    name: "{{ ssm_package_url }}"
    disable_gpg_check: yes # https://github.com/aws/amazon-ssm-agent/issues/235
    state: present
  when: ansible_pkg_mgr == "dnf"

- name: RedHat | Manage aws ssm agent service
  service:
    name: "{{ ssm_service }}"
    state: started
    enabled: yes

- name: RedHat | Configure sudo with aws ssm agent
  copy:
    content: "{{ allow_sudo | ternary('ssm-user ALL=(ALL) NOPASSWD:ALL', '#User rules for ssm-user') }}"
    dest: /etc/sudoers.d/ssm-agent-users
    mode: '0440'
