---
# Install aws ssm agent on Suse family system

- name: Suse | Install aws ssm agent
  zypper:
    name: "{{ ssm_package_url }}"
    disable_gpg_check: yes
    state: present

- name: Suse | Manage aws ssm agent service
  service:
    name: "{{ ssm_service }}"
    state: started
    enabled: yes

- name: Suse | Configure sudo with aws ssm agent
  copy:
    content: "{{ allow_sudo | ternary('ssm-user ALL=(ALL) NOPASSWD:ALL', '#User rules for ssm-user') }}"
    dest: /etc/sudoers.d/ssm-agent-users
    mode: '0440'

- name: Suse | Register on-premise instance
  command: "amazon-ssm-agent -register -code {{ activation_code }} -id {{ activation_id }} -region {{ aws_region }}"
  notify: Linux | Restart amazon ssm agent
  when:
    - activation_code
    - activation_id
    - aws_region
