---
# Install aws ssm agent on Windows family system

- name: Windows | Install aws ssm agent
  win_package:
    path: "{{ ssm_package_url }}"
    product_id: amazon-ssm-agent
    creates_path: C:\Program Files\Amazon\SSM\amazon-ssm-agent.exe
    arguments:
      - /install
      - /quiet
      - /norestart
    state: present
  when:
    - not activation_code
    - not activation_id
    - not aws_region

- name: Windows | Manage aws ssm agent service
  win_service:
    name: "{{ ssm_service }}"
    start_mode: auto
    state: started
  when:
    - not activation_code
    - not activation_id
    - not aws_region
