---
- name: Verify
  hosts: all
  tasks:
    - set_fact:
        amazon_ssm_service: "amazon-ssm-agent"

    - set_fact:
        amazon_ssm_service: "snap.amazon-ssm-agent.amazon-ssm-agent.service"
      when:
        - ansible_facts['distribution'] == "Ubuntu"
        - ansible_facts['distribution_major_version']|int >= 18

    - name: Linux | Amazon ssm agent service should be started and enabled
      service:
        name: "{{ amazon_ssm_service }}"
        state: started
        enabled: yes
      register: ssm_service_result

    - name: Linux | Sudo file used by Amazon ssm user should be present
      stat:
        path: /etc/sudoers.d/ssm-agent-users
      register: ssm_sudo_result

    - name: Linux | Verify commands outputs
      assert:
        that:
          - ssm_service_result.changed == false
          - ssm_sudo_result.stat.exists
        success_msg: "All tests passed"
