name: molecule

on:
  push:
  pull_request:
  schedule:
    - cron: '0 18 * * sun'

jobs:
  test:
    name: ${{ matrix.image }}
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        image:
          - ansible-centos:8
          - ansible-centos:7
          - ansible-centos:6
          - ansible-fedora:32
          - ansible-fedora:31
          - ansible-fedora:30
          - ansible-fedora:29
          - ansible-fedora:28
          - ansible-fedora:27
          - ansible-fedora:26
          - ansible-ubuntu:20.04
          - ansible-ubuntu:18.04
          - ansible-ubuntu:16.04
          - ansible-debian:10
          - ansible-debian:9
          - ansible-debian:8
          - ansible-oraclelinux:8
          - ansible-oraclelinux:7
          - ansible-oraclelinux:6
          - ansible-amazonlinux:2
          - ansible-amazonlinux:1
          - ansible-opensuse:leap
          - ansible-opensuse:tumbleweed
          - ansible-opensuse:13.2
          - ansible-opensuse:15
          - ansible-opensuse:15.1
          - ansible-archlinux:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Molecule
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint yamllint molecule-docker docker
      
      - name: Block fake aws metadata
        run: sudo iptables -t nat -I PREROUTING -p tcp -d 169.254.169.254 --dport 80 -j DNAT --to-destination 127.0.0.1 

      - name: Test Ansible role
        run: molecule test
        env: 
          image: ${{ matrix.image }}

      - name: Test Ansible role with check_mode enable
        run: molecule check
        env: 
          image: ${{ matrix.image }}
